name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        
      - name: install TS
        run: npm install typescript
      
      - name: npm install
        run: npm install

      - name: run buildRun.sh
        run: sh buildRun.sh

      - name: run commitKatacoda.sh
        run: bash commitKatacoda.sh

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: externals/katacoda-scenarios-dev/
