name: CI Windows PR
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: 	windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        
      - name: install TS
        run: npm install typescript
      
      - name: npm install
        run: npm install

      - name: run checkout.ps1
        run: .\checkout.ps1

      - name: run buildRun.ps1 --user ${{ github.actor }} --branch ${{ github.event.pull_request.head.ref }} ${{ github.event.inputs.logLevel }}
        run: .\buildRun.ps1 --user ${{ github.actor }} --branch ${{ github.event.pull_request.head.ref }} ${{ github.event.inputs.logLevel }}
