name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: 	windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        
      - name: install TS
        run: npm install typescript
      
      - name: npm install
        run: npm install

      - name: run checkout.ps1
        run: .\checkout.ps1

      - name: run buildRun.ps1
        run: .\buildRun.ps1
